<?php

echo "<h1>Hello!</h1>";

//echo $this->tag->linkTo(["CRUD/signup", "Sign Up Here!", 'class' => 'btn btn-primary']);
echo $this->tag->linkTo(["CRUD/signup", "Create task!", 'class' => 'btn btn-success']);

if ($users->count() > 0) {
    ?>
    <div>⠀</div>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th class="mx-auto">Nr.</th>
            <th class="mx-auto">Task</th>
            <th class="mx-auto">Description</th>
            <th class="mx-auto">Edit</th>
            <th class="mx-auto">Delete</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Task quantity: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <?php $deleteUrl = 'localhost/CRUD/delete?id=' . $user->idnew_table ?>
            <tr>
                <td><?php echo $user->idnew_table;?></td>
                <td><?php echo $user->task_name;?></td>
                <td><?php echo $user->task_description;?></td>
                <td > <?php echo $this->tag->linkTo(["CRUD/taskEdit/index/" . $user->idnew_table, "Edit", 'class' => 'btn btn-primary mx-auto']);?> </td>
                <td><?php echo $this->tag->linkTo(['CRUD/taskDelete/index/' . $user->idnew_table, 'Delete', 'class' => 'btn btn-danger mx-auto']) ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}