<?php

echo "<h1>Hello!</h1>";

echo $this->tag->linkTo(["/taskCreate", "Create task!", 'class' => 'btn btn-success']);

if ($tasks->count() > 0) {
    ?>
    <div>⠀</div>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th class="mx-auto">Nr.</th>
            <th class="mx-auto">Task</th>
            <th class="mx-auto">Description</th>
            <th class="mx-auto">Edit</th>
            <th class="mx-auto">Delete</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Task quantity: <?php echo $tasks->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($tasks as $task) { ?>
            <tr>
                <td><?php echo $task->idnew_table;?></td>
                <td><?php echo $task->task_name;?></td>
                <td><?php echo $task->task_description;?></td>
                <td > <?php echo $this->tag->linkTo(["/taskEdit/index/" . $task->idnew_table, "Edit", 'class' => 'btn btn-primary mx-auto']);?> </td>
                <td><?php echo $this->tag->linkTo(['/taskDelete/index/' . $task->idnew_table, 'Delete', 'class' => 'btn btn-danger mx-auto']) ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}