<h2>Here you can delete task</h2>

<?php echo $this->tag->form(["CRUD/taskDelete/delelete/"]); ?>

<p>
    <label for="idnew_table">ID</label><br>
    <?php echo $this->tag->textField(["idnew_table", 'value' => $user->idnew_table, 'disabled' => 'disabled']); ?>
</p>

<p>
    <label for="task_name">Task name</label><br>
    <?php echo $this->tag->textField(["task_name", 'value' => $user->task_name]); ?>
</p>

<p>
    <label for="task_description">Task description</label><br>
    <?php echo $this->tag->textField(["task_description", 'value' => $user->task_description]); ?>
</p>

<p>
    <?php echo $this->tag->submitButton(["Do you really want to delete task?", "CRUD/taskDelete/delelete/", 'class' => 'btn btn-danger mx-auto']); ?>
</p>

</form>
