<h2>Here you can edit task</h2>

<?php echo $this->tag->form(["/taskEdit/edidit/"]); ?>

<p>
    <label hidden for="idnew_table">ID</label><br>
    <?php echo $this->tag->textField(["idnew_table", 'value' => $task->idnew_table, 'hidden' => 'true' ]); ?>
</p>

<p>
    <label for="task_name">Task name</label><br>
    <?php echo $this->tag->textField(["task_name", 'value' => $task->task_name]); ?>
</p>

<p>
    <label for="task_description">Task description</label><br>
    <?php echo $this->tag->textField(["task_description", 'value' => $task->task_description]); ?>
</p>

<p>
    <?php echo $this->tag->submitButton(["Save task", "/taskEdit/edidit/", 'class' => 'btn btn-primary mx-auto']); ?>
</p>

</form>